name: ci_cpp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # サブモジュールを再帰的にチェックアウトする
        submodules: 'recursive'
        fetch-depth: 0  # リポジトリの全履歴をフェッチする

    - name: Install C++ compiler and tools
      run: sudo apt-get update && sudo apt-get install -y g++ make cmake git

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/kmyk/online-judge-verify-helper.git@master

    - name: Get list of changed files
      id: files
      run: |
        MAIN_LATEST_COMMIT=$(git rev-parse origin/main)
        git diff --name-only $MAIN_LATEST_COMMIT ${{ github.sha }} | grep '\.cpp$' > changed_files.txt
        echo "::set-output name=list::$(cat changed_files.txt)"


    - name: Compile and Test Changed C++ Files
      run: |
        if [ -s changed_files.txt ]; then
          while IFS= read -r file; do
            g++ "$file" -o "${file%.*}.out" -w -std=c++20 -I library/ac-library/
            oj t -d "$(dirname "$file")/test/" -c "./${file%.*}.out"
          done < changed_files.txt
        else
          echo "No .cpp files have changed."
        fi
