name: ci_cpp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # サブモジュールを再帰的にチェックアウトする
        submodules: 'recursive'

    - name: Install C++ compiler and tools
      run: sudo apt-get update && sudo apt-get install -y g++ make cmake git

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/kmyk/online-judge-verify-helper.git@master

    - name: Run Cpp scripts
      run: |
        find ./contests -type f -name '*.cpp' -exec sh -c 'dir="{}"; echo $dir; base="$(dirname "$dir")"; g++ $dir -w -std=c++20 -I library/ac-library/ && oj t -d  "$base/test/";' \;

